from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass
from enum import Enum
from typing import Any, Mapping

from .belief import BeliefEngine
from .environment import Environment
from .graph_state import GraphStateExporter
from .models import BeliefState, GraphState, HiddenWorld, MissionAction, ObservationBatch, PublicState
from .planners import Planner


class LoopPhase(str, Enum):
    """Minimal orchestration phases needed for the no-RL adaptive loop."""

    UNINITIALIZED = "uninitialized"
    READY_TO_PLAN = "ready_to_plan"
    MISSION_PLANNED = "mission_planned"
    COMPLETE = "complete"
    REVEALED = "revealed"


@dataclass(frozen=True, slots=True)
class RoundTransition:
    """Observable transition generated by one complete mission round."""

    mission: MissionAction
    observations: ObservationBatch
    public_state_before: PublicState
    public_state_after: PublicState
    belief_before: BeliefState
    belief_after: BeliefState
    graph_before: GraphState
    graph_after: GraphState
    next_mission: MissionAction | None
    done: bool
    simulator_metrics: dict[str, Any]


class AdaptiveMissionLoop:
    """Orchestrate plan -> survey -> Bayes -> GraphState -> replan.

    The loop is deliberately planner-agnostic. It owns no hidden ecological
    truth; only the Environment owns latent occupancy. Hidden truth becomes
    available through `reveal()` only after the loop reaches COMPLETE.

    CURRENT DEFAULT for M4: the episode completes when field budget is exhausted.
    Later product-state work may add an explicit operator/fast-forward completion
    event, but reveal must remain gated and outside the planner path.
    """

    def __init__(
        self,
        environment: Environment,
        planner: Planner,
        prior_by_site: Mapping[str, float],
        *,
        exporter: GraphStateExporter | None = None,
    ) -> None:
        self._environment = environment
        self._planner = planner
        self._prior_by_site = dict(prior_by_site)
        self._exporter = exporter or GraphStateExporter()

        self._phase = LoopPhase.UNINITIALIZED
        self._public_state: PublicState | None = None
        self._belief: BeliefState | None = None
        self._graph_state: GraphState | None = None
        self._pending_mission: MissionAction | None = None

    @property
    def phase(self) -> LoopPhase:
        return self._phase

    @property
    def current_public_state(self) -> PublicState:
        self._require_initialized()
        assert self._public_state is not None
        return deepcopy(self._public_state)

    @property
    def current_belief(self) -> BeliefState:
        self._require_initialized()
        assert self._belief is not None
        return deepcopy(self._belief)

    @property
    def current_graph_state(self) -> GraphState:
        self._require_initialized()
        assert self._graph_state is not None
        return deepcopy(self._graph_state)

    def reset(self, seed: int | None = None) -> GraphState:
        """Reset environment, belief, graph state and reveal gate."""

        public_state = self._environment.reset(seed=seed)
        belief = BeliefEngine.initialize(
            self._prior_by_site,
            confirmed_sites={public_state.initial_detection},
        )
        graph_state = self._exporter.export(public_state, belief)

        self._public_state = public_state
        self._belief = belief
        self._graph_state = graph_state
        self._pending_mission = None

        if public_state.remaining_budget == 0:
            self._phase = LoopPhase.COMPLETE
            self._environment._allow_reveal()
        else:
            self._phase = LoopPhase.READY_TO_PLAN

        return deepcopy(graph_state)

    def plan_next(self) -> MissionAction:
        """Return the pending mission, creating it exactly once if necessary."""

        self._require_initialized()
        if self._phase in (LoopPhase.COMPLETE, LoopPhase.REVEALED):
            raise RuntimeError("Cannot plan after the mission loop is complete.")

        if self._pending_mission is not None:
            return self._pending_mission

        assert self._public_state is not None
        assert self._graph_state is not None
        constraints = self._exporter.planner_constraints(self._public_state)
        mission = self._planner.plan(
            self._graph_state,
            remaining_budget=self._public_state.remaining_budget,
            constraints=constraints,
        )
        if mission.total_cost <= 0 or not mission.allocations:
            raise RuntimeError(
                "Planner returned an empty mission while positive budget remains."
            )

        self._pending_mission = mission
        self._phase = LoopPhase.MISSION_PLANNED
        return mission

    def execute_pending(self) -> RoundTransition:
        """Execute the displayed mission, update belief, and produce the next plan."""

        self._require_initialized()
        if self._phase is not LoopPhase.MISSION_PLANNED or self._pending_mission is None:
            raise RuntimeError("No pending mission is available to execute.")

        assert self._public_state is not None
        assert self._belief is not None
        assert self._graph_state is not None

        mission = self._pending_mission
        public_before = deepcopy(self._public_state)
        belief_before = deepcopy(self._belief)
        graph_before = deepcopy(self._graph_state)

        observations, done, metrics = self._environment.step(mission)
        public_after = self._environment.current_public_state
        constraints_after = self._exporter.planner_constraints(public_after)
        q_by_site = constraints_after["q_by_site"]
        belief_after = BeliefEngine.update(
            self._belief,
            observations,
            q_by_site,
        )
        graph_after = self._exporter.export(public_after, belief_after)

        self._public_state = public_after
        self._belief = belief_after
        self._graph_state = graph_after
        self._pending_mission = None

        if done:
            self._phase = LoopPhase.COMPLETE
            self._environment._allow_reveal()
            next_mission = None
        else:
            self._phase = LoopPhase.READY_TO_PLAN
            next_mission = self.plan_next()

        return RoundTransition(
            mission=mission,
            observations=observations,
            public_state_before=public_before,
            public_state_after=deepcopy(public_after),
            belief_before=belief_before,
            belief_after=deepcopy(belief_after),
            graph_before=graph_before,
            graph_after=deepcopy(graph_after),
            next_mission=next_mission,
            done=done,
            simulator_metrics=dict(metrics),
        )

    def run_round(self) -> RoundTransition:
        """Convenience method for CLI/tests: plan if needed, then execute it."""

        if self._phase is LoopPhase.READY_TO_PLAN:
            self.plan_next()
        return self.execute_pending()

    def reveal(self) -> HiddenWorld:
        """Reveal true extent only after completion; never usable by a planner."""

        self._require_initialized()
        if self._phase is not LoopPhase.COMPLETE:
            raise RuntimeError("Reveal is only available after the loop is complete.")
        hidden_world = self._environment.reveal()
        self._phase = LoopPhase.REVEALED
        return hidden_world

    def _require_initialized(self) -> None:
        if self._phase is LoopPhase.UNINITIALIZED:
            raise RuntimeError("AdaptiveMissionLoop has not been reset yet.")
